WcfService/MediApp/Controllers/DiseasesController.cs
using ComunicationControllers;
using EntityModels;
using MediApp.Models;
using MediApp.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MediApp.Controllers
{
    public class DiseasesController : Controller
    {
        static DbServices.PatientsContext db = new DbServices.PatientsContext(WcfConfig.WcfUri);
        // GET: Diseases
        public ActionResult Index()
        {
            return View();
        }
        
        public ActionResult Survey()
        {
            ViewBag.Message = "Wstępna diagnoza chorób";
            return View(new SurveyModel());
        }
        
        [HttpPost]
        public ActionResult Survey(SurveyModel model)
        {
            ViewBag.Message = "Wstępna diagnoza chorób";
            WcfController.saveSurvey(new EntityModels.Output
            {
                Answer = model.responses
            });

            return RedirectToAction("Index", "Home");
        }

        public ActionResult DiseasesHistory()
        {
            ViewBag.Message = "Historia przebytych chorób";

            return View(new SharedModels.IllnessModel());
        }

        [MediAuthorize(Roles = RolesKind.PATIENT)]
        public ActionResult Illnesses(int id)
        {
            ViewBag.Message = "Historia chorób";
            //var pat = db.TablePatient.Where(e => e.Pesel == SessionPersister.User.Pesel);
            //int id = pat.First().Id;
            var model = new SharedModels.IllnessModel { IdPatient = id };
            return View(model);
        }
    }
}

WcfService/MediApp/Controllers/MedicController.cs
using EntityModels;
using MediApp.Models;
using MediApp.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MediApp.Controllers
{
    public class MedicController : Controller
    {
        [MediAuthorize(Roles = RolesKind.MEDIC)]
        public ActionResult Index()
        {
            return View();
        }

        [MediAuthorize(Roles = RolesKind.MEDIC)]
        public ActionResult Patients()
        {
            ViewBag.Message = "Dane pacjentów";
            return View(WcfController.getAllPatients().AsEnumerable());
        }
        [MediAuthorize(Roles = RolesKind.MEDIC)]
        public ActionResult PatientDetails(int id)
        {
            ViewBag.Message = "Szczegóły pacjenta:";
            return View(WcfController.getPatient(id));
        }
        [MediAuthorize(Roles = RolesKind.MEDIC)]
        public ActionResult MeasuresPartial(int id)
        {
            ViewBag.Message = "Pomiary pacjenta:";
            return PartialView(WcfController.getMeasures(id));
        }
        [MediAuthorize(Roles = RolesKind.MEDIC)]
        public ActionResult PatientsIlnessPartial(int id)
        {
            ViewBag.Message = "Choroby pacjenta:";
            return PartialView(WcfController.getIllness(id));
        }
        [MediAuthorize(Roles = RolesKind.MEDIC)]
        public ActionResult CreateIllness(int id)
        {
            var model = new SharedModels.IllnessModel { IdPatient = id };
            return View(model);
        }
        [MediAuthorize(Roles = RolesKind.MEDIC)]
        public ActionResult CreateIllnessResult(SharedModels.IllnessModel illModel)
        {
            illModel.Date = DateTime.Now;
          //  illModel.IdPatient = id;
            WcfController.addIlnnessToDb(illModel);
            return RedirectToAction("PatientDetails",new { id = illModel.IdPatient });
        }

    }
}

WcfService/MediApp/Controllers/SharedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MediApp.Models;
using MediApp.Security;
using EntityModels;

namespace MediApp.Controllers
{
    public class SharedController : Controller
    {
        
        [ChildActionOnly]
        public ActionResult _PatientPartial()
        {
            PatientPartialModel model = new PatientPartialModel();

            if (null != SessionPersister.User &&
               SessionPersister.User.Roles.Any(r => r.Name == RolesKind.PATIENT))
                model.IsPatient = true;
            else
                model.IsPatient = false;

            return PartialView(model);
        }

        [ChildActionOnly]
        public ActionResult _MedicPartial()
        {
            MedicPartialModel model = new MedicPartialModel();

            if (null != SessionPersister.User &&
               SessionPersister.User.Roles.Any(r => r.Name == RolesKind.MEDIC))
                model.IsMedic = true;
            else
                model.IsMedic = false;

            return PartialView(model);
        }
    }
}

WcfService/MediApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - MediApp</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top ">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MediApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Strona domowa", "Index", "Home")</li>
                    <li>@Html.ActionLink("O nas", "About", "Home")</li>
                    <li>@Html.ActionLink("Kontakt", "Contact", "Home")</li>
                     @{ Html.RenderAction("_PatientPartial", "Shared"); }
                     @{ Html.RenderAction("_MedicPartial", "Shared"); }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="backgroundCont">
    </div>
    <div class="container body-content container-semi">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - MediApp</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

WcfService/MediApp/Views/Shared/_MedicPartial.cshtml
@using MediApp.Models
@model MedicPartialModel

@if (Model.IsMedic)
{
    <li>@Html.ActionLink("Pacjenci", "Patients", "Medic")</li>
}

WcfService/MediApp/Views/Shared/_PatientPartial.cshtml
@using MediApp.Models
@model PatientPartialModel

@if(Model.IsPatient)
{
    <li>@Html.ActionLink("Badanie", "Survey", "Diseases")</li>
    <li>@Html.ActionLink("Historia chorób", "DiseasesHistory", "Diseases")</li>    
}